### ISSUE TITLE
Corrigir exceção ao consultar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [jeanfurquim/dsclient-bootcamp-devsuperior#1]
Olá Jean, tudo bem?
Sou o Alexandre e estou corrigindo a sua atividade.

Seu trabalho já está aceito, parabéns! Mas para ficar 100%, favor incluir o tratamento de exceções. Ao **consultar** um cliente com id inexistente retorna um erro **500**.

Abraço e bons estudos

**Comment by jeanfurquim** [comment]
Ola Prof Alexandre, tudo e voce?

 

Ok Obrigado. Corrigido o erro. Tratamento já existia mas havia um erro.

 

Obrtigado!

 

De: Alexandre ***@***.***> 
Enviada: quinta-feira, 20 de maio de 2021 11:55
Para: jeanfurquim/dsclient-bootcamp-devsuperior ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [jeanfurquim/dsclient-bootcamp-devsuperior] Corrigir exceção ao consultar cliente com id inexistente (#1)

 

Olá Jean, tudo bem?
Sou o Alexandre e estou corrigindo a sua atividade.

Seu trabalho já está aceito, parabéns! Mas para ficar 100%, favor incluir o tratamento de exceções. Ao consultar um cliente com id inexistente retorna um erro 500.

Abraço e bons estudos
